import sys; sys.path.append('./statcruncher')

import datetime

from mongokit import ObjectId
from sortedcontainers import SortedListWithKey

from statcruncher.query import Calculate, QueryHelpers

queryhelpers = QueryHelpers('2014-12-20', '2014-12-22')
my_query = {'Opp': 'WAS'}
my_query.update(queryhelpers.datetime_range())

calculate_dk = Calculate(my_query, 'draftkings')
calculate_fd = Calculate(my_query, 'fanduel')

print calculate_dk.print_gamelogs()

test_gamelog = {
    'PlusMinus': 19.0,
    'FT': 10.0,
    'TOV': 2.0,
    'Tm': 'POR',
    'GmSc': 38.8,
    'FG': 11.0,
    'DRB': 5.0,
    'Rk': 30.0,
    'Opp': 'OKC',
    'G': 30.0,
    'AST': 11.0,
    'Season': 'reg',
    'HomeAway': '@',
    'TP': 8.0,
    'PF': 1.0,
    'Date': datetime.datetime(2014, 12, 23, 0, 0),
    'WinLoss': 'W (+4)',
    'FGA': 21.0,
    'GS': 1.0,
    'TPA': 12.0,
    'STL': 2.0,
    'Age': '24-161',
    'TRB': 6.0,
    'FTA': 11.0,
    'BLK': 0.0,
    'PTS': 40.0,
    'Player': 'lillada01',
    'MP': '45:46',
    'Year': '2015',
    'ORB': 1.0
}

def test_calc_dfs_score_from_gamelog_draftkings():
    assert calculate_dk.calc_dfs_score_from_gamelog(test_gamelog) == 72.5


def test_calc_dfs_score_from_gamelog_fanduel():
    assert calculate_fd.calc_dfs_score_from_gamelog(test_gamelog) == 65.7


def test_create_datetime_range():
    assert queryhelpers.datetime_range() == {
        'Date': {
            '$gte': datetime.datetime(2014, 12, 20, 0, 0),
            '$lt': datetime.datetime(2014, 12, 22, 0, 0)
        }
    }


def test_is_double_double():
    assert calculate_dk.is_double_triple_double(
        [10, 10, 10, 5, 3, 2]) == 3.00


def test_is_triple_double():
    assert calculate_dk.is_double_triple_double(
        [12, 11, 4, 3, 2]) == 1.50


def test_is_not_double_or_triple_double():
    assert calculate_dk.is_double_triple_double(
        [9, 8, 4, 3]) == 0

def test_create_dfs_score_sorted_list():
    assert calculate_dk.create_dfs_scores_sorted_list() == SortedListWithKey([
        {'score': 31.0,
         'gamelog': {
            u'PlusMinus': 0.0,
            u'FT': 2.0,
            u'TOV': 3.0,
            u'Tm': u'PHO',
            u'GmSc': 12.9,
            u'FG': 6.0,
            u'DRB': 5.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 27.0,
            u'AST': 4.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 2.0,
            u'PF': 2.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 11.0,
            u'GS': 1.0,
            u'TPA': 5.0,
            u'STL': 1.0,
            u'Age': u'28-229',
            u'TRB': 6.0,
            u'FTA': 2.0,
            u'BLK': 0.0,
            u'PTS': 16.0,
            u'Player': u'dragigo01',
            u'MP': u'30:48',
            u'Year': 2015,
            u'_id': ObjectId('54989fea3a4cfc5309df998e'),
            u'ORB': 1.0
        }},
        {'score': 26.5,
         'gamelog': {
            u'PlusMinus': 3.0,
            u'FT': 2.0,
            u'TOV': 2.0,
            u'Tm': u'PHO',
            u'GmSc': 9.0,
            u'FG': 3.0,
            u'DRB': 4.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 29.0,
            u'AST': 1.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 0.0,
            u'PF': 5.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 3.0,
            u'GS': 1.0,
            u'TPA': 0.0,
            u'STL': 0.0,
            u'Age': u'21-188',
            u'TRB': 8.0,
            u'FTA': 6.0,
            u'BLK': 4.0,
            u'PTS': 8.0,
            u'Player': u'lenal01',
            u'MP': u'23:33',
            u'Year': 2015,
            u'_id': ObjectId('5498b54f3a4cfc5309e21cea'),
            u'ORB': 4.0,
        }},
        {'score': 20.5,
         'gamelog': {
            u'PlusMinus': 8.0,
            u'FT': 2.0,
            u'TOV': 2.0,
            u'Tm': u'PHO',
            u'GmSc': 8.5,
            u'FG': 7.0,
            u'DRB': 2.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 29.0,
            u'AST': 1.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 1.0,
            u'PF': 2.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 14.0,
            u'GS': 1.0,
            u'TPA': 3.0,
            u'STL': 0.0,
            u'Age': u'25-110',
            u'TRB': 2.0,
            u'FTA': 2.0,
            u'BLK': 0.0,
            u'PTS': 17.0,
            u'Player': u'morrima02',
            u'MP': u'35:37',
            u'Year': 2015,
            u'_id': ObjectId('5498b54b3a4cfc5309e21c7b'),
            u'ORB': 0.0
        }},
        {'score': 17.75,
         'gamelog': {
            u'PlusMinus': 9.0,
            u'FT': 2.0,
            u'TOV': 1.0,
            u'Tm': u'PHO',
            u'GmSc': 5.2,
            u'FG': 4.0,
            u'DRB': 2.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 21.0,
            u'AST': 3.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 0.0,
            u'PF': 1.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 12.0,
            u'GS': 0.0,
            u'TPA': 0.0,
            u'STL': 0.0,
            u'Age': u'25-317',
            u'TRB': 3.0,
            u'FTA': 2.0,
            u'BLK': 0.0,
            u'PTS': 10.0,
            u'Player': u'thomais02',
            u'MP': u'24:01',
            u'Year': 2015,
            u'_id': ObjectId('54989ca03a4cfc5309df3731'),
            u'ORB': 1.0
        }},
        {'score': 17.5,
         'gamelog': {
            u'PlusMinus': 11.0,
            u'FT': 1.0,
            u'TOV': 3.0,
            u'Tm': u'PHO',
            u'GmSc': 7.1,
            u'FG': 5.0,
            u'DRB': 3.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 29.0,
            u'AST': 0.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 2.0,
            u'PF': 4.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 7.0,
            u'GS': 0.0,
            u'TPA': 3.0,
            u'STL': 0.0,
            u'Age': u'28-329',
            u'TRB': 4.0,
            u'FTA': 1.0,
            u'BLK': 0.0,
            u'PTS': 13.0,
            u'Player': u'greenge01',
            u'MP': u'17:43',
            u'Year': 2015,
            u'_id': ObjectId('5498b5ec3a4cfc5309e2305b'),
            u'ORB': 1.0
        }},
        {'score': 17.0,
         'gamelog': {
            u'PlusMinus': 9.0,
            u'FT': 0.0,
            u'TOV': 1.0,
            u'Tm': u'PHO',
            u'GmSc': 6.6,
            u'FG': 2.0,
            u'DRB': 4.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 29.0,
            u'AST': 0.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 0.0,
            u'PF': 2.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 2.0,
            u'GS': 0.0,
            u'TPA': 0.0,
            u'STL': 1.0,
            u'Age': u'26-111',
            u'TRB': 6.0,
            u'FTA': 0.0,
            u'BLK': 2.0,
            u'PTS': 4.0,
            u'Player': u'plumlmi01',
            u'MP': u'21:27',
            u'Year': 2015,
            u'_id': ObjectId('5498ad193a4cfc5309e11c27'),
            u'ORB': 2.0
        }},
        {'score': 12.5,
         'gamelog': {
            u'PlusMinus': 9.0,
            u'FT': 0.0,
            u'TOV': 1.0,
            u'Tm': u'PHO',
            u'GmSc': 4.8,
            u'FG': 5.0,
            u'DRB': 0.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 29.0,
            u'AST': 1.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 1.0,
            u'PF': 2.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 9.0,
            u'GS': 0.0,
            u'TPA': 2.0,
            u'STL': 0.0,
            u'Age': u'25-110',
            u'TRB': 0.0,
            u'FTA': 2.0,
            u'BLK': 0.0,
            u'PTS': 11.0,
            u'Player': u'morrima03',
            u'MP': u'29:12',
            u'Year': 2015,
            u'_id': ObjectId('5498b2f13a4cfc5309e1d560'),
            u'ORB': 0.0
        }},
        {'score': 11.25,
         'gamelog': {
            u'PlusMinus': 3.0,
            u'FT': 2.0,
            u'TOV': 2.0,
            u'Tm': u'PHO',
            u'GmSc': 3.8,
            u'FG': 2.0,
            u'DRB': 4.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 25.0,
            u'AST': 0.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 0.0,
            u'PF': 2.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 3.0,
            u'GS': 1.0,
            u'TPA': 1.0,
            u'STL': 0.0,
            u'Age': u'29-230',
            u'TRB': 5.0,
            u'FTA': 2.0,
            u'BLK': 0.0,
            u'PTS': 6.0,
            u'Player': u'tuckepj01',
            u'MP': u'18:48',
            u'Year': 2015,
            u'_id': ObjectId('5498af363a4cfc5309e15a5c'),
            u'ORB': 1.0
        }},
        {'score': 6.5,
         'gamelog': {
            u'PlusMinus': 3.0,
            u'FT': 2.0,
            u'TOV': 0.0,
            u'Tm': u'PHO',
            u'GmSc': 1.5,
            u'FG': 0.0,
            u'DRB': 2.0,
            u'Rk': 29.0,
            u'Opp': u'WAS',
            u'G': 12.0,
            u'AST': 0.0,
            u'Season': u'reg',
            u'HomeAway': u'@',
            u'TP': 0.0,
            u'PF': 1.0,
            u'Date': datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss': u'W (+12)',
            u'FGA': 2.0,
            u'GS': 0.0,
            u'TPA': 0.0,
            u'STL': 0.0,
            u'Age': u'31-027',
            u'TRB': 2.0,
            u'FTA': 2.0,
            u'BLK': 1.0,
            u'PTS': 2.0,
            u'Player': u'randosh01',
            u'MP': u'10:03',
            u'Year': 2015,
            u'_id': ObjectId('5498b1883a4cfc5309e1a75c'),
            u'ORB': 0.0
        }}
        ],  key=lambda val: -val['score'])


def test_remove_dnps():
    print calculate_dk.remove_dnps()
    assert calculate_dk.remove_dnps() == [  
        {  
            u'PlusMinus':9.0,
            u'FT':2.0,
            u'TOV':1.0,
            u'Tm':u'PHO',
            u'GmSc':5.2,
            u'FG':4.0,
            u'DRB':2.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':21.0,
            u'AST':3.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':0.0,
            u'PF':1.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':12.0,
            u'GS':0.0,
            u'TPA':0.0,
            u'STL':0.0,
            u'Age':u'25-317',
            u'TRB':3.0,
            u'FTA':2.0,
            u'BLK':0.0,
            u'PTS':10.0,
            u'Player':u'thomais02',
            u'MP': u'24:01',
            u'Year':2015,
            u'_id':ObjectId('54989ca03a4cfc5309df3731'),
            u'ORB':1.0
        },
        {  
            u'PlusMinus':5.0,
            u'FT':5.0,
            u'TOV':2.0,
            u'Tm':u'PHO',
            u'GmSc':12.6,
            u'FG':6.0,
            u'DRB':7.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':29.0,
            u'AST':3.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':0.0,
            u'PF':3.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':15.0,
            u'GS':1.0,
            u'TPA':3.0,
            u'STL':1.0,
            u'Age':u'25-012',
            u'TRB':9.0,
            u'FTA':6.0,
            u'BLhK':1.0,
            u'PTS':17.0,
            u'Player':u'bledser01',
            u'MP': u'28:48',
            u'Year':2015,
            u'_id':ObjectId('54989eb03a4cfc5309df7826'),
            u'ORB':2.0
        },
        {  
            u'PlusMinus':0.0,
            u'FT':2.0,
            u'TOV':3.0,
            u'Tm':u'PHO',
            u'GmSc':12.9,
            u'FG':6.0,
            u'DRB':5.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':27.0,
            u'AST':4.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':2.0,
            u'PF':2.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':11.0,
            u'GS':1.0,
            u'TPA':5.0,
            u'STL':1.0,
            u'Age':u'28-229',
            u'TRB':6.0,
            u'FTA':2.0,
            u'BLK':0.0,
            u'PTS':16.0,
            u'Player':u'dragigo01',
            u'MP': u'30:48', 
            u'Year':2015,
            u'_id':ObjectId('54989fea3a4cfc5309df998e'),
            u'ORB':1.0
        },
        {  
            u'PlusMinus':9.0,
            u'FT':0.0,
            u'TOV':1.0,
            u'Tm':u'PHO',
            u'GmSc':6.6,
            u'FG':2.0,
            u'DRB':4.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':29.0,
            u'AST':0.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':0.0,
            u'PF':2.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':2.0,
            u'GS':0.0,
            u'TPA':0.0,
            u'STL':1.0,
            u'Age':u'26-111',
            u'TRB':6.0,
            u'FTA':0.0,
            u'BLK':2.0,
            u'PTS':4.0,
            u'Player':u'plumlmi01',
            u'MP':u'21:27',
            u'Year':2015,
            u'_id':ObjectId('5498ad193a4cfc5309e11c27'),
            u'ORB':2.0
        },
        {  
            u'PlusMinus':3.0,
            u'FT':2.0,
            u'TOV':2.0,
            u'Tm':u'PHO',
            u'GmSc':3.8,
            u'FG':2.0,
            u'DRB':4.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':25.0,
            u'AST':0.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':0.0,
            u'PF':2.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':3.0,
            u'GS':1.0,
            u'TPA':1.0,
            u'STL':0.0,
            u'Age':u'29-230',
            u'TRB':5.0,
            u'FTA':2.0,
            u'BLK':0.0,
            u'PTS':6.0,
            u'Player':u'tuckepj01',
            u'MP':u'18:48',
            u'Year':2015,
            u'_id':ObjectId('5498af363a4cfc5309e15a5c'),
            u'ORB':1.0
        },
        {  
            u'PlusMinus':3.0,
            u'FT':2.0,
            u'TOV':0.0,
            u'Tm':u'PHO',
            u'GmSc':1.5,
            u'FG':0.0,
            u'DRB':2.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':12.0,
            u'AST':0.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':0.0,
            u'PF':1.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':2.0,
            u'GS':0.0,
            u'TPA':0.0,
            u'STL':0.0,
            u'Age':u'31-027',
            u'TRB':2.0,
            u'FTA':2.0,
            u'BLK':1.0,
            u'PTS':2.0,
            u'Player':u'randosh01',
            u'MP':u'10:03',
            u'Year':2015,
            u'_id':ObjectId('5498b1883a4cfc5309e1a75c'),
            u'ORB':0.0
        },
        {  
            u'PlusMinus':9.0,
            u'FT':0.0,
            u'TOV':1.0,
            u'Tm':u'PHO',
            u'GmSc':4.8,
            u'FG':5.0,
            u'DRB':0.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':29.0,
            u'AST':1.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':1.0,
            u'PF':2.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':9.0,
            u'GS':0.0,
            u'TPA':2.0,
            u'STL':0.0,
            u'Age':u'25-110',
            u'TRB':0.0,
            u'FTA':2.0,
            u'BLK':0.0,
            u'PTS':11.0,
            u'Player':u'morrima03',
            u'MP':u'29:12',
            u'Year':2015,
            u'_id':ObjectId('5498b2f13a4cfc5309e1d560'),
            u'ORB':0.0
        },
        {  
            u'PlusMinus':8.0,
            u'FT':2.0,
            u'TOV':2.0,
            u'Tm':u'PHO',
            u'GmSc':8.5,
            u'FG':7.0,
            u'DRB':2.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':29.0,
            u'AST':1.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':1.0,
            u'PF':2.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':14.0,
            u'GS':1.0,
            u'TPA':3.0,
            u'STL':0.0,
            u'Age':u'25-110',
            u'TRB':2.0,
            u'FTA':2.0,
            u'BLK':0.0,
            u'PTS':17.0,
            u'Player':u'morrima02',
            u'MP':u'35:37',
            u'Year':2015,
            u'_id':ObjectId('5498b54b3a4cfc5309e21c7b'),
            u'ORB':0.0
        },
        {  
            u'PlusMinus':3.0,
            u'FT':2.0,
            u'TOV':2.0,
            u'Tm':u'PHO',
            u'GmSc':9.0,
            u'FG':3.0,
            u'DRB':4.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':29.0,
            u'AST':1.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':0.0,
            u'PF':5.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':3.0,
            u'GS':1.0,
            u'TPA':0.0,
            u'STL':0.0,
            u'Age':u'21-188',
            u'TRB':8.0,
            u'FTA':6.0,
            u'BLK':4.0,
            u'PTS':8.0,
            u'Player':u'lenal01',
            u'MP':u'23:33',
            u'Year':2015,
            u'_id':ObjectId('5498b54f3a4cfc5309e21cea'),
            u'ORB':4.0
        },
        {  
            u'PlusMinus':11.0,
            u'FT':1.0,
            u'TOV':3.0,
            u'Tm':u'PHO',
            u'GmSc':7.1,
            u'FG':5.0,
            u'DRB':3.0,
            u'Rk':29.0,
            u'Opp':u'WAS',
            u'G':29.0,
            u'AST':0.0,
            u'Season':u'reg',
            u'HomeAway':u'@',
            u'TP':2.0,
            u'PF':4.0,
            u'Date':datetime.datetime(2014, 12, 21, 0, 0),
            u'WinLoss':u'W (+12)',
            u'FGA':7.0,
            u'GS':0.0,
            u'TPA':3.0,
            u'STL':0.0,
            u'Age':u'28-329',
            u'TRB':4.0,
            u'FTA':1.0,
            u'BLK':0.0,
            u'PTS':13.0,
            u'Player':u'greenge01',
            u'MP':u'17:43',
            u'Year':2015,
            u'_id':ObjectId('5498b5ec3a4cfc5309e2305b'),
            u'ORB':1.0
        }
    ]